### ISSUE TITLE
Provide element templates bundle as release artifact

### ISSUE THREAD

**Issue by menski** [camunda/connectors-bundle#14]
__Is your feature request related to a problem? Please describe.__

As a user I want to be able to download all element templates corresponding to the connectors include in a connectors bundle.

__Describe the solution you'd like__

During the release of the connectors bundle package all corresponding element templates into a single archive and upload it to the connector bundle release.

__Describe alternatives you've considered__

- Manually download all element templates (current situation)
- Create a script to download element templates for users #11 

__Additional context__

At a later point modelers can use the URL of the release artifact to easy import all containing element templates.

**Comment by menski** [comment]
@nikku and @tmetzke right now our element templates in the github release doesn't contain version numbers, i.e. every release has the same artifact with the same name, what do you think about including the version in the release name? Or would that lead to a situation if as a User I download multiple versions of the same element template and put them in my modeler it is a conflict? How is that handled?

**Comment by nikku** [comment]
@menski Two options: We can either ignore versioning for now (and await user feedback) _OR_ implement it right. 

----

What does _implementing it right_ imply (from my point of view):

* Versioning requires: A `version` number to be set, and incremented with each new change. 
* Old templates must remain accessible so that upgrading works (upgrading requires both old and new templates to be around).

What could we do:

* Add a version tag (number) to the connectors and increment it with each release
* We have to ship templates in a way that discourages _overriding_ (i.e. ship it in a `connectors-bundle-0.1.1` folder and encourage putting that folder into your `.camunda/element-templates` folder). 

This would ensure:

* New templates do not override old templates
* Usages of templates can be upgrade from one version to the other

However, from the user point of view it is not desirable to incorporate new connector templates _unless_ there is actual changes. Otherwise we'll force them into useless upgrades where nothing actually changed:

![image](https://user-images.githubusercontent.com/58601/195609237-a68aea63-c501-4ba3-8b24-a8ca65419929.png)


----

What would it imply if we don't set `version`:

* Templates won't be upgraded; modeler will simply always use the latest version; as a result no (new) defaults will be set, icons updated. If we remove old templates the UI will indicate that ("not found"):

![image](https://user-images.githubusercontent.com/58601/195609436-58960e2d-8bae-4844-99e9-5b4ebb08847d.png)

**Comment by menski** [comment]
Thanks Nico, I think that is very helpful insights. From your answer I take away that versioning is not a thing yet, so we should keep the current approach of bundling templates with the same name until our tooling could actually handle versioning.

**Comment by nikku** [comment]
What would it take to introduce namespacing as suggested https://github.com/camunda/connectors-bundle/issues/14#issuecomment-1277628310 into our bundles?

Parse JSON, extract version, rename connector to `slack-connector{-${version}).json`.

**Comment by nikku** [comment]
Maintaining a version in our templates is something that we can establish as a practice fairly quickly.

**Comment by nikku** [comment]
I did extract my comment into a follow-up. I believe it is actionable and we could benefit from it: https://github.com/camunda/team-connectors/issues/170.
