### ISSUE TITLE
Discover how to add support for self-signed SSL certificates for rest connector in self-managed environments

### ISSUE THREAD

**Issue by mbiciin** [camunda/connectors-bundle#180]
__What should we do?__

One idea is to check if connector secrets support ssl certificate (base64 format). We could copy the content of the certificate and add it as a secret. 

__Why should we do it?__

#108 

__See also__

https://camunda.slack.com/archives/C02JLRNQQ05/p1671024704623129

**Comment by bastiankoerber** [comment]
@mbiciin & @igpetrov  what is the best practice (technically). If we are using the input field, could these cause some security issues?

**Comment by berndruecker** [comment]
Quick thoughts on this:

1. I would not add the certificate directly into the process model as Input field, because certificates might differ depending on the environment (e.g. dev connects to dev systems while prod connects to other prod systems). I would not see it as a security risk though (certificates are not confidential in contrast to secrets). 
2. The Secret Store has a maximum capacity of 64kb per entry (https://cloud.google.com/secret-manager/quotas), which is too small for SSL certificates (https://www.google.com/search?client=firefox-b-d&q=ssl+certifcate+size). So this is not really an option.
3. If we think about SaaS, we could probably leverage the GCP Certificate Manager (https://cloud.google.com/certificate-manager/docs/certificates), but we would need to check if and how we can use it. Challenges / Tasks:

  * We can only access the certificate manager from the Connector Runtime, but not the Proxy function where we need the certificate.
  * There might be a challenge to get the right certificate loaded into the HTTP stack correctly, I know that @falko did this successfully in the past, worth to check-in with him
  * We would need some place in the console to manage custom certificates for clients

My gut feeling is: If we see custom certificates as a common problem in SaaS, we should probably invest in proper certificate management. If we don't see it as priority, we might think again about some workaround.

For self-managed, the story might differ, but this could be abstracted (exactly like we did with the Secret Manager).

**Comment by bastiankoerber** [comment]
i will double check, if the customer was a SAAS or SM customer.

**Comment by bastiankoerber** [comment]
https://camunda.slack.com/archives/C02JLRNQQ05/p1671024704623129

The customer targes SM

**Comment by mbiciin** [comment]
We are waiting for feedback from @falko. I will put this task on hold for now, as suggested by @berndruecker.

**Comment by falko** [comment]
Customers using client certificates are usually very careful with security topics. Therefore, storing certificates in the process model or process variables is not an option.

I used the Java keystore and configured the Apache HTTP Client to use it. Many popular REST libraries seem to lack support for this. The Open Banking API even combines client certificates with additional authentication tokens.

How about a quick meeting to discuss the details?

**Comment by berndruecker** [comment]
Howdy @falko - also happy to jump on a meeting - but I guess sharing the code would also be helpful probably in advance. 
And yes, I could imagine that we need to change the HTTP client used. I will organize a meeting and send an invite to @falko  and @mbiciin

**Comment by berndruecker** [comment]
Code from @falko how he did the custom keystore:

```java
private ApiClient getDefaultApiClient() {
    // *
    System.setProperty("javax.net.ssl.keyStore", "/home/falko/git/joc-tech-spike/hsbcob.p12");
    System.setProperty("javax.net.ssl.keyStorePassword", "hsbcob");
    System.setProperty("javax.net.ssl.keyStoreType", "PKCS12");
    // */
    System.setProperty("javax.net.debug", "ssl"); // TLS debug
    // System.setProperty("javax.net.debug", "ssl:handshake:verbose:keymanager:trustmanager"); //
    // very verbose debug

    ApiClient defaultClient = new ApiClient(HttpClients.createSystem());
    defaultClient.setBasePath("https://secure.sandbox.ob.hsbc.co.uk/obie/open-banking/v3.1/aisp");

    // Configure OAuth2 access token for authorization: TPPOAuth2Security
    OAuth TPPOAuth2Security = (OAuth) defaultClient.getAuthentication("TPPOAuth2Security");
    TPPOAuth2Security.setAccessToken(accessToken);
    return defaultClient;
  }
```

**Comment by berndruecker** [comment]
Possible paths forward:

1. Check if Guava/Google can use the System Environment variables to setup the keystore properly
2. If it can't, switch to Apache HTTP client (but needs refactoring for the overall code)

Interesting Tools:
- https://keystore-explorer.org/

**Comment by bastiankoerber** [comment]
> Possible paths forward:
> 
> 1. Check if Guava/Google can use the System Environment variables to setup the keystore properly
> 2. If it can't, switch to Apache HTTP client (but needs refactoring for the overall code)
> 
> Interesting Tools:
> 
> * https://keystore-explorer.org/

before we are going path 2, let's have a discussion. I want to discuss investment vs. outcome
