### ISSUE TITLE
Connection Timeout Field in Out-of-the-Box Connectors

### ISSUE THREAD

**Issue by Chris-Maechler** [camunda/connectors-bundle#587]
The element template of the REST connector and others have this field and I noticed several problems:
- Why no feel? Timeout could come from a variable. (Just one example why we would want feel: calculate timeout of a batch operation depending on the number of items.)
- The regex for validation is `^([0-9]*$)|(secrets.*$)`, why?

If it should start with `secrets.` then the correct regex is `"secrets\\..*"` and not `"secrets.*"`. You could remove the paranthesis and get the same result (now ^ is only applied to first part), so I guess it should have been `"^([0-9]*|secrets\\..*)$"`, but I doubt ^ and $ are required, only a match makes sense, not just a find. So `[0-9]*|secrets\\..*` should be sufficient.

**Comment by chillleader** [comment]
Thanks @Chris-Maechler - both points are valid. We should allow FEEL and change the regex. I'm moving this to `Ready` status and will pick it up in the near future.

**Comment by chillleader** [comment]
After a bit of experimenting I found this regex to be the most suitable here:
`^(=.+|[0-9]+|secrets\\..+)$`

- `^` and `$` are actually needed, otherwise, it will also match e.g. `invalid_value_secrets.non_existing`
- replaced wildcard `*` quantifiers with `+` to exclude empty strings
- added the first part `=.+` to cover the FEEL expressions

**Comment by chillleader** [comment]
This is fixed and will be released in Connectors `0.20.0`.
